### ISSUE TITLE
Need doc for QRI-back

### ISSUE THREAD

**Issue by ArteenGalstyan** [TwoAs/QRI-Webapp#6]
The following needs to be added to QRI-back.md:

- [x] Schema
  - [x] Models
  - [x] Handlers

**Comment by aaronbrown404** [comment]
I'm confused by this issue. Does the file (QRI-back.md) need to be created? Or do you want this added to timeline.md?

**Comment by ArteenGalstyan** [comment]
Yeah we need a new file `QRI-back.md` that will list all the models and handlers as described in our schema.
